### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by mensong** [Nomango/configor#105]
struct WriteTextParam
{
	std::wstring file;
	std::wstring text;
	bool append;

	CONFIGOR_BIND(wjson::value, WriteTextParam, REQUIRED(file), REQUIRED(text), REQUIRED(append));
};

使用wchar_t时编译错误。

**Comment by Nomango** [comment]
这是因为 `REQUIRED(file)` 其实是 `REQUIRED(file, "file")` 的缩写。

宽字符类型绑定需要指定宽字符字段名，例如：

```cpp
struct WriteTextParam
{
  std::wstring file;
  std::wstring text;
  bool append;

  CONFIGOR_BIND(wjson::value, WriteTextParam, REQUIRED(file, L"file"), REQUIRED(text, L"text"), REQUIRED(append, L"append"));
};
```

为了方便，也可以自定义一个转换宏

```cpp
#define WREQUIRED(field) REQUIRED(field, L ## #field)

struct WriteTextParam
{
  std::wstring file;
  std::wstring text;
  bool append;

  CONFIGOR_BIND(wjson::value, WriteTextParam, WREQUIRED(file), WREQUIRED(text), WREQUIRED(append));
};
```

这块说明补充到 [wiki](https://github.com/Nomango/configor/wiki/Custom-conversion-%28zh%29) 了
