### ISSUE TITLE
to_value question

### ISSUE THREAD

**Issue by dongliushi** [Nomango/configor#109]
### Description
Using a vector to initialize a value can be problematic.

According to the debugging results, the problem occurs when the to_value function does not set the value type.

### Reproduction steps
```
#include "configor/configor.hpp"

#include <vector>

int main()
{
    std::vector<int> v{};
    configor::value a{v};
    assert(a.is_array() == true);
}
```

### Expected vs. actual results

The program should run normally. But it has the following error:
Assertion failed: a.is_array() == true, file D:/mycode/configor/tests/t.cpp, line 10

### Compiler and operating system
mingw(gcc-13) on windows10 22h2

**Comment by Nomango** [comment]
The issue has been solved. Thank you!
