### ISSUE TITLE
Json序列化带有中文会出错，也无法正常迭代

### ISSUE THREAD

**Issue by ButterFlyYe** [Nomango/configor#36]
Json序列化带有中文会出错，也无法正常迭代
迭代器在碰到中文字符时会抛出异常，wjson也是一样

**Comment by ButterFlyYe** [comment]
是我的问题 JSON数组只能用for

**Comment by Nomango** [comment]
@ButterFlyYe 数组也可以正常使用迭代器的，如果确实有问题，可以提供代码看看
