### ISSUE TITLE
序列化时key值顺序问题

### ISSUE THREAD

**Issue by Crazing** [Nomango/configor#37]
json对象内部委托std::map实现，key值是有序的，不是插入序，可以留个接口让key值按照插入序来序列化吗？

**Comment by Nomango** [comment]
@Crazing 建议用第三方库替换std::map吧，比如 [nlohmann/fifo_map](https://github.com/nlohmann/fifo_map)

拉取一下最新的configor代码，然后声明 `fifo_json` 替换 `json` 来保证插入序
```cpp
struct fifo_json_args : json_args
{
    template <class _Kty, class _Ty, class... _Args>
    using object_type = nlohmann::fifo_map<_Kty, _Ty, _Args...>;
};

using fifo_json = configor::basic_config<fifo_json_args>;
```

**Comment by Crazing** [comment]
好的，我测试一下
