### ISSUE TITLE
序列化包含中文出错

### ISSUE THREAD

**Issue by F11st** [Nomango/configor#42]
你好，在使用configor时，json包含中文字符串时在序列化时会出错，具体代码如下
```c++
#include <iostream>
#include "json.hpp"
int main() {
	using namespace std;
	using namespace configor;
	json j = "宽带连接";
	cout << j.dump() << endl;
	return 0;
}
```
dump()异常
> 0x76D7B4B2 处(位于 Project1.exe 中)引发的异常: Microsoft C++ 异常: configor::configor_serialization_error，位于内存位置 0x00DEEA98 处。
> 0x76D7B4B2 处(位于 Project1.exe 中)引发的异常: Microsoft C++ 异常: [rethrow]，位于内存位置 0x00000000 处。
> 0x76D7B4B2 处(位于 Project1.exe 中)有未经处理的异常: Microsoft C++ 异常: configor::configor_serialization_error，位于内存位置 0x00DEEA98 处。

**Comment by Nomango** [comment]
@F11st 这是由于在中文环境下，Visual Studio 和 Windows 终端使用的编码都是 gb2312，但 configor 仅支持 unicode。

Visual Studio 使用 utf-8 比较困难（也是醉了，都2021年了还有编译器不默认支持utf-8），建议直接忽略编码，对中文不做处理：

```cpp
// 使用 encoding::ignore 忽略编码
json j = "宽带连接";
cout << j.dump<encoding::ignore>() << endl;
```
