### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by ntzxtyz** [Nomango/configor#47]
异常：
terminate called after throwing an instance of 'configor::configor_deserialization_error'
  what():  config deserialization error: unexpected token 'end_of_input'
环境：
gcc: 11.1.0
clang: 12.0.1
第一次运行时无错，后来运行就会抛出异常。

**Comment by Nomango** [comment]
@ntzxtyz 提供下代码看看，这个问题一般是读取文件失败导致的，可以检查下fstream有没有问题

**Comment by ntzxtyz** [comment]
> @ntzxtyz 提供下代码看看，这个问题一般是读取文件失败导致的，可以检查下fstream有没有问题

嗯，是读取文件出错，我用configor构建的json读取就没有问题。
是否考虑到换行符？

**Comment by Nomango** [comment]
@ntzxtyz 那就是你的路径写错了吧，打开文件后有检查fstream是否可用吗

**Comment by Nomango** [comment]
@ntzxtyz 可以这样判断一下文件流是否有问题
```cpp
std::ifstream file("config.json");
if (!file.is_open()) {
        throw std::runtime_error("config.json not found");
}
configor::json config;
file >> config;
```

**Comment by ntzxtyz** [comment]
谢谢，是我没检查。
