### ISSUE TITLE
在0.9.11中 编译的时候 报错configor_conversion.hpp:106:123: fatal error: template instantiation depth exceeds maximum of 2048

### ISSUE THREAD

**Issue by LanSilence** [Nomango/configor#51]
./include/configor/configor_conversion.hpp:106:123: fatal error: template instantiation depth exceeds maximum of 2048 (use -ftemplate-depth= to increase the maximum)
     _ConfTy, _Ty, typename std::enable_if<std::is_void<decltype(config_bind<_Ty>::from_config(std::declval<const _ConfTy&>(), std::declval<_Ty&>()))>::value, void>::type>
                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
compilation terminated.

**Comment by Nomango** [comment]
@lcpbule 提供下你的编译环境和报错部分的代码看看

**Comment by lcpbule** [comment]
> @lcpbule 提供下你的编译环境和报错部分的代码看看
编译器GCC  7.5，CXX_FLAG := -g -fPIC -O0 -Wall -std=c++11 -ftemplate-depth=2048
一开始 "depth exceeds maximum of 2048"这里报错900就使用参数-ftemplate-depth=2048调至2048，还是会有别的模板有报错。

**Comment by Nomango** [comment]
@lcpbule @wd-hub 单测在G++ 9、10、11和MinGW 8.1上是成功的，7.x版本我还没测过，可以先通过升级gcc解决，具体问题还要再看看

**Comment by Nomango** [comment]
@LanSilence @wd-hub 最新版已经修复

**Comment by wd-hub** [comment]
> @LanSilence @wd-hub 最新版已经修复
好的，谢谢
