### ISSUE TITLE
不能正确解析integer

### ISSUE THREAD

**Issue by ntzxtyz** [Nomango/configor#52]
std::string的data()内容如下：
{
    "code": 0,
    "session": "sIMIG9Fe"
}
抛出一下错误：
terminate called after throwing an instance of 'configor::configor_type_error'
  what():  config type error: cannot convert type 'string' to type 'integer' (implicitly)

**Comment by ntzxtyz** [comment]
试着static-cast成string，又抛“不能把integer转换为string”了

**Comment by Nomango** [comment]
@ntzxtyz 不是bug，是使用方式有问题，可以阅读一下readme中的[取值方式](https://github.com/Nomango/configor#%E5%8F%96%E5%80%BC%E6%96%B9%E5%BC%8F)部分

**Comment by Nomango** [comment]
不能使用static_cast转换是因为类型本身就不可以转换，比如下面的代码本身就是错误的
```cpp
int i = 10;
std::string str = static_cast<std::string>(i);
```
