### ISSUE TITLE
示例中的json::wrap提示没有这个成员（？）

### ISSUE THREAD

**Issue by AbrasiveBoar902** [Nomango/configor#54]
我是完全按照例子上写的啊）

**Comment by Nomango** [comment]
@AbrasiveBoar902 使用的是最新版本的代码吗？可能是因为有更新

**Comment by AbrasiveBoar902** [comment]
> @AbrasiveBoar902 使用的是最新版本的代码吗？可能是因为有更新

我用的是最新的release 0.9.11

**Comment by Nomango** [comment]
@AbrasiveBoar902 想起来上次想发版，github崩了。。重新发了版，更新下就可以了

**Comment by AbrasiveBoar902** [comment]
0.9.12可以了
