### ISSUE TITLE
emm关于wrap?

### ISSUE THREAD

**Issue by AbrasiveBoar902** [Nomango/configor#55]
`auto arr = se.get<json::array_type>();
for (unsigned int i = 0; i < arr.size(); i++)
{
	getversion Ver;
	stringstream ss;
	ss << arr[i];
	ss >> json::wrap(Ver);
}`
这样可以正常获取arr[i]中的内容并写入Ver,但是
`getversion Ver;
arr[i].wrap(Ver);`
这样获取不到任何内容
所以arr[i].wrap(Ver)作用是啥啊)

**Comment by AbrasiveBoar902** [comment]
还有`json.get<json::array_type>()`前几次编译报错说没有匹配的重载函数，后来编译又通过了（没改东西）

**Comment by Nomango** [comment]
@AbrasiveBoar902 json::wrap是个static函数，没有 `j.wrap(xx)` 的用法，只能 `json::wrap(xx)`
看你的例子其实不需要wrap，直接`Ver = arr[i]`就可以了。wrap的作用你可以理解为把json格式的stream内容映射到结构体中（或反过来），看看[与自定义类型转换](https://github.com/Nomango/configor#与自定义类型转换)这块文档

**Comment by Nomango** [comment]
比如这段代码
```cpp
std::ifstream file("config.json");
json j;
file >> j;

MyConfig c = j;
```
可以简写为
```cpp
std::ifstream file("config.json");
MyConfig c;
file >> json::wrap(c);
```

**Comment by AbrasiveBoar902** [comment]
> @AbrasiveBoar902 json::wrap是个static函数，没有 `j.wrap(xx)` 的用法，只能 `json::wrap(xx)`
> 看你的例子其实不需要wrap，直接`Ver = arr[i]`就可以了。wrap的作用你可以理解为把json格式的stream内容映射到结构体中（或反过来），看看[与自定义类型转换](https://github.com/Nomango/configor#%E4%B8%8E%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2)这块文档
谢谢

**Comment by AbrasiveBoar902** [comment]
在读取空文件并判断is_object()会发生异常

**Comment by Nomango** [comment]
@AbrasiveBoar902 当然，空文件不是合法的json
