### ISSUE TITLE
解析问题

### ISSUE THREAD

**Issue by AbrasiveBoar902** [Nomango/configor#56]
如何解析要求传入iter_begin和iter_end的数据？或如何从char数组中解析？

**Comment by AbrasiveBoar902** [comment]
不支持流

**Comment by Nomango** [comment]
支持的，parse接受的参数是std::istream、std::string、const char*、std::FILE*

**Comment by AbrasiveBoar902** [comment]
如何用[fast_io](https://github.com/tearosccebe/fast_io)从文件中读取并解析呢?(

**Comment by Nomango** [comment]
@AbrasiveBoar902 configor和标准库结合的比较紧密，而且没有支持任意iter的输入输出方式，我觉得只能用fast_io读取文件后转成标准库的stream或string才可以操作，但这就失去了fast_io的意义
