### ISSUE TITLE
Linux下编译使用报template instantiation depth exceeds maximum of错误

### ISSUE THREAD

**Issue by wngxao** [Nomango/configor#64]

**Comment by Nomango** [comment]
@wngxao 之前版本有过这个问题，已经修复了，如果还有问题贴一下gcc版本号吧

**Comment by kandynan** [comment]
> @wngxao 之前版本有过这个问题，已经修复了，如果还有问题贴一下gcc版本号吧

能告知是在哪个版本修复的吗？

**Comment by Nomango** [comment]
> > @wngxao 之前版本有过这个问题，已经修复了，如果还有问题贴一下gcc版本号吧
> 
> 能告知是在哪个版本修复的吗？

在这个issue #51 修复的，v0.9.13版本吧。
