### ISSUE TITLE
赋值double问题

### ISSUE THREAD

**Issue by Cuihaixu** [Nomango/configor#65]
伪代码:
// 1638341381.633359
double time = get_current_time();

// 初始化赋值
json j = {
     {"time": time}
};

// 获取值时变成float
j["time"].get<double>()
// 打印  1.63834e+09

是需要额外设置什么参数吗？

**Comment by Nomango** [comment]
@Cuihaixu 应该是打印的代码有问题吧
```cpp
double d = 1638341381.633359;
std::cout << d << std::endl;
std::cout << std::fixed << std::setprecision(12) << d << std::endl;

// output:
// 1.63834e+09
// 1638341381.633358955383
```

**Comment by Cuihaixu** [comment]
@Nomango 感谢大佬，确实是打印函数问题。不好意思
