### ISSUE TITLE
as_string报错没有构造函数

### ISSUE THREAD

**Issue by sannmizu** [Nomango/configor#70]
非常不错的轮子，但是我在使用中遇到如下问题

using namespace std;
using namespace configor;
json j;
j["123"] = "12345";
string s = j["123"];

vs2017会报错: configor::detail::json_serializer<configor::basic_config<configor::json_args>,configor::basic<_Args>::default_encoding,cofigor::basic_config<_Args>::default_encoding>类没有构造函数

**Comment by sannmizu** [comment]
打错啦，是string s = j["123"].as_string()

**Comment by sannmizu** [comment]
v0.9.11版本没有问题，v0.9.12版本开始出现这个问题

**Comment by Nomango** [comment]
@sannmizu 感谢反馈，v0.9.15已修复
