### ISSUE TITLE
C字符串的结束符的解析问题

### ISSUE THREAD

**Issue by eustrainLee** [Nomango/configor#73]
应该在json.hpp的json_lexer::scan函数内的switch中加入一个case：
``` C++
case '\0':
result = token_type::end_of_input;
break;
```
以应对可能从流上读入C字符串末尾的结束符，以免抛出异常:
```
config deserialization error: unexpected character '\u0000'
```

**Comment by Nomango** [comment]
@eustrainLee 这个要讨论一下，c++的流正常不会返回'\0'的，eof才是真的结束符，除非是自定义的流输入，那何时结束应该由用户自己判断，比如当输入流来自std::cin时，用户希望以'\n'作为结束符，那么在实现iadapter时应该这么实现：
```cpp
struct myadapter : public iadapter
{
    // 读取一个字符
    virtual char read() override
    {
        // 读到换行符结束
        char ch = std::cin.get();
        if (ch == '\n')
            return std::char_traits<char>::eof(); // 返回eof
        return ch;
    }
};
```
同样，对于'\0'是否也应该作为用户自定义结束符的一种呢？

**Comment by eustrainLee** [comment]
> @eustrainLee 这个要讨论一下，c++的流正常不会返回'\0'的，eof才是真的结束符，除非是自定义的流输入，那何时结束应该由用户自己判断，比如当输入流来自std::cin时，用户希望以'\n'作为结束符，那么在实现iadapter时应该这么实现：
> 
> ```c++
> struct myadapter : public iadapter
> {
>     // 读取一个字符
>     virtual char read() override
>     {
>         // 读到换行符结束
>         char ch = std::cin.get();
>         if (ch == '\n')
>             return std::char_traits<char>::eof(); // 返回eof
>         return ch;
>     }
> };
> ```
> 
> 同样，对于'\0'是否也应该作为用户自定义结束符的一种呢？

往往我们输入的时候往往是从文件或者socket读入的，比如在我当前的项目中，使用自定义streambuf的方式将socket包装成iostream，其中underflow函数是这么写的
```C++
int underflow() override {
    // auto n = ::recv(sock, buf, BUFSIZE, 0); // 读取的数据包含 '\0'
    auto n = ::read(sock, buf, BUFSIZE); // 读取的数据不包含 '\0'
    return n > 0 ? (setg(buf, buf, buf + n), *gptr()) : EOF;
}
```
当我使用::recv实现它的时候使用istream去读取数据的时候就能读取到对方发过来的'\0'。
还有可能使用string存储二进制数据，里面也是有可能在末尾存在'\0'
如果把raw data转变成cooked data往往会带来不必要的开销， 仅仅是为了消除一个'\0'就要将整个数据遍历一遍，为什么不在解析的时候做这件事呢？

**Comment by Nomango** [comment]
@eustrainLee 最近比较忙，刚刚把处理\0的代码加上去了，感谢反馈~
