### ISSUE TITLE
VS2017编译例子报错

### ISSUE THREAD

**Issue by tiany520** [Nomango/configor#76]
#include <string>
#include <iostream>
#include <sstream>
#include <configor/json.hpp>

using namespace configor;

// 用户类
struct User
{
	int user_id;
	std::string user_name;

	JSON_BIND(User, user_id, user_name);
};

int main(int argc, char** argv)
{
	std::stringstream s("{\"user_id\": 10001, \"user_name\": \"John\"}");

	// 解析json内容，并反序列化到user对象
	User user;
	s >> json::wrap(user);

	// 序列化user对象并输出
	std::cout << configor::json::wrap(user) << std::endl; // {"user_id":10001,"user_name":"John"}

	return 0;
}

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2064	项不会计算为接受 2 个参数的函数	WindscribeFindNode	f:\usr\local\configor-0.9.15\include\configor\configor_basic.hpp	916	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2064	项不会计算为接受 3 个参数的函数	WindscribeFindNode	f:\usr\local\configor-0.9.15\include\configor\configor_basic.hpp	886

**Comment by Nomango** [comment]
@tiany520 目测在main函数的第一行，双引号没有转义，会导致编译错误
