### ISSUE TITLE
json无法操作中文，读取会弹出configor_serialization_error

### ISSUE THREAD

**Issue by becnit** [Nomango/configor#77]
vs2022         c++14

	json j = {
		{"name", "JSON 解析和序列化"},
		{"item", "测试JSON文件加载"}
	};

	wjson wj = {
		{L"name", L"JSON 解析和序列化"},
		{L"item", L"测试JSON文件加载"}
	};

	wcout << L"wchar_t\t" << wj << endl;
	cout << "char\t" << j << endl;            // configor_serialization_error
	
处理中文只能用wjson吗

**Comment by Nomango** [comment]
@becnit 可以处理中文的，可以贴一下configor_serialization_error里面具体的信息看看
