### ISSUE TITLE
如何用 std::unordered_map 替换 std::map

### ISSUE THREAD

**Issue by becnit** [Nomango/configor#78]
struct fifo_json_args : json_args
{
	template <class _Kty, class _Ty, class... _Args>
	using object_type = nlohmann::fifo_map<_Kty, _Ty, _Args...>;
};

// fifo_json 是按插入序排列的
using fifo_json = configor::basic_config<fifo_json_args>;

例程里，用fifom_map替换std::map，使用时编译错误，vs2022

fifo_json j1 = { {"2.name", "2"}, {"1.name", "1"}, {"0.name", "0"} };
fifo_map.hpp(341,19): error C2039: "add_key": 不是 "std::less<std::basic_string<char,std::char_traits<char>,std::allocator<char>>>" 的成员

**Comment by becnit** [comment]
大佬能给指导下吗

**Comment by Nomango** [comment]
@becnit 最近比较忙，我会关注一下这个问题

**Comment by Nomango** [comment]
@becnit 更正了一下README中fifo_map的用法
```cpp
struct fifo_json_args : json_args
{
    template <class _Kty, class _Ty, class... _Args>
    using object_type = nlohmann::fifo_map<_Kty, _Ty>;
};

// fifo_json 是按插入序排列的
using fifo_json = configor::basic_config<fifo_json_args>;
```

但是std::unordered_map确实不能使用，因为它在gcc上要求第二个模板参数类型必须是complete type，详见 [#224](https://github.com/Nomango/configor/runs/6665292603?check_suite_focus=true)
