### ISSUE TITLE
JSON_BIND error C2061: syntax error: identifier 'json'

### ISSUE THREAD

**Issue by alluLinger** [Nomango/configor#80]
Fix by add namespace 'configor':
`#define JSON_BIND(value_type, ...) CONFIGOR_BIND_WITH_CONF(configor::json, value_type, __VA_ARGS__)`

https://github.com/Nomango/configor/blob/14f10d541ed991327e8caca8a2aa92c39ae5903a/include/configor/json.hpp#L74

---

![图片](https://user-images.githubusercontent.com/21037233/157887554-a102701a-4c44-4b7a-b721-51f752e7b158.png)

**Comment by Nomango** [comment]
@alluLinger 感谢反馈，已经修复了哈，#86
