### ISSUE TITLE
请问当前有内存泄露的问题吗

### ISSUE THREAD

**Issue by duzhen1996** [Nomango/configor#81]
我们打算在一个系统中使用这个来频繁读一个配置文件。这里面会建立大量configor::json的临时对象。请问当前的实现的所有数据成员都在栈区吗，如果在堆区，其析构问题是不是已经搞定了？

我看您的文档里面没有提到析构的问题。

**Comment by Nomango** [comment]
@duzhen1996 会自动回收json里的数据的，默认使用std::allocator申请内存，一般不需要关注是如何回收的
