### ISSUE TITLE
About the way to qeury if a key is accessiable

### ISSUE THREAD

**Issue by XShinHe** [Nomango/configor#82]
When I ask if there exist a key in the json object, I use:
`bool ifhaskey(configor::json js, std::string key) {return !js[key].is_null();}`
But it will add null type assoicated with this key to original json. When I just want to ask a key if it is can be accessiable and don't want to set an additional key to mark it null value, which method can be used?

**Comment by Nomango** [comment]
@XShinHe you can use `if (j.count(key)) { xxx }` instead, like `std::map::count`

**Comment by XShinHe** [comment]
Thx @Nomango
