### ISSUE TITLE
序列化输出至json文件的参考代码好像报错

### ISSUE THREAD

**Issue by KrisHugo** [Nomango/configor#85]
使用visual studio code
```
    std::ofstream ofstream("./output.json");
    ofstream << j << endl;
```
在ofstream报错信息提示：不允许使用不完整的类型；
同时在<< 处报错

除了序列化输出至文件外，貌似序列化输出流是正常的，我不能够肯定这是什么原因，我的C++很烂

![image](https://user-images.githubusercontent.com/31278991/170618853-22eea207-d6a9-4490-a7aa-a664b3b9a5a9.png)

**Comment by KrisHugo** [comment]
对了，我使用了push_back将这个json类做成了array：
![image](https://user-images.githubusercontent.com/31278991/170620189-e76f1d5e-f7db-4e5e-a1c9-4e173052105c.png)

我的json文件的大致内容是这样的：
![image](https://user-images.githubusercontent.com/31278991/170620086-d4669a38-fcdd-4019-9bdd-a9e8c089170f.png)

**Comment by Nomango** [comment]
emm，从报错位置猜测应该是因为没有引入<fstream>这个头文件导致的
