### ISSUE TITLE
与自定义类型BIND后，支持json里不填一些字段么？顺序必须一致么？

### ISSUE THREAD

**Issue by Minghui-BD** [Nomango/configor#90]
发现这样几个现象：
* 如果自定义类型里对应的字段不填，json to 自定义类的转换时，会抛异常；
* 如果自定义类型里嵌套使用自定义类型，json to 自定义类的转换时，嵌套使用的自定义类型信息会丢；

**Comment by Minghui-BD** [comment]
临时workaround：
#define CONFIGOR_FROM_CONF(field) if (c.count(#field) > 0) {c.at(#field).get(v.field);}

**Comment by Nomango** [comment]
@Minghui-BD 第一点必须手写config_binder的特化实现，来处理某些情况下字段缺失的逻辑，第二点应该不会的，可以贴一下具体代码

**Comment by Minghui-BD** [comment]
@Nomango 我发现两个点是同一个root-cause，原因是自定义类型的字段是全的，json配置里是可能缺失，顺序也不保证的，所以我改了下CONFIGOR_FROM_CONF，先判断下count来达成这个想要的目的：
```
#define CONFIGOR_FROM_CONF(field) if (c.count(#field) > 0) {c.at(#field).get(v.field);}
```

**Comment by Nomango** [comment]
@Minghui-BD 最新版增加了一种更灵活的宏，像这样：
```cpp
struct User
{
    int user_id;
    std::string user_name;

    CONFIGOR_BIND(json, User, REQUIRED(user_id), OPTIONAL(user_name));
};
```
使用 `CONFIGOR_BIND` 宏，然后为每个字段指定required或optional，对于optional的字段会做空值判断。看看这个功能是不是你需要的？

**Comment by Minghui-BD** [comment]
@Nomango 嗯嗯，CONFIGOR_BIND 可以满足遇到的场景。
